//text - error massage, field - is error validate input
export default Mn.Object.extend({
    NULL_REQUEST:{text: 'Передана пустая строка вместо json', field: false},
    JSON_PARSE_EXCEPTION:{text: 'Ошибка парсинга json', field: false},
    WRONG_URL:{text: 'Несуществующий endpoint', field: false},
    WRONG_OR_EMPTY_LOGIN:{text: 'Пользователя с таким логином нет', field: true},
    WRONG_OR_EMPTY_PASSWORD:{text: 'Пароль недопустимого формата или пустой пароль', field: true},
    LOGIN_ALREADY_EXISTS:{text: 'Пользователь с таким логином уже зарегистрирован', field: true},
    LOGIN_DOESNOT_EXIST:{text: 'Пользователя с таким логином нет', field: true},
    PASSWORD_NOT_MATCH:{text: 'Неправильный пароль', field: true},
    WRONG_TOKEN_PASSED:{text: 'Несуществующий токен пользователя', field: false},
    USER_IS_NOT_TEACHER:{text: 'Пользователь с этим логином не является преподавателем', field: false},
    USER_IS_NOT_STUDENT:{text: 'Пользователь с этим логином не является студентом', field: false},
    WRONG_OR_EMPTY_FIRSTNAME:{text: 'Имя пользователя  недопустимого формата или пустое имя', field: false},
    WRONG_OR_EMPTY_LASTNAME:{text: 'Фамилия пользователя  недопустимого формата или пустая фамилия', field: false},
    WRONG_PATRONYMIC:{text: 'Отчество пользователя  недопустимого формата', field: false},
    EMPTY_POSITION:{text: 'Пустая должность преподавателя', field: false},
    EMPTY_DEPARTMENT:{text: 'Пустое название кафедры', field: false},
    EMPTY_EXAM_NAME:{text: 'Пустое название предмета', field: false},
    WRONG_EXAM_ID:{text: 'Неверный номер экзамена или экзамен создан другим преподавателем', field: false},
    EXAM_ALREADY_EXISTS:{text: 'Экзамен с таким именем для этого семестра уже есть', field: false},
    NO_READY_EXAM_FOR_THIS_SEMESTER:{text: 'Экзамен с таким номером не существует или не готов или предназначен для другого семестра', field: false},
    EXAM_IS_READY:{text: 'Делается попытка изменить содержание или установить состояние “готов” для экзамена, который уже переведен в состояние “готов”', field: false},
    EMPTY_QUESTION_BODY:{text: 'Пустой текст вопроса', field: false},
    NOT_ENOUGH_QUESTIONS:{text: 'Количество вопросов, задаваемых студенту, больше, чем общее количество вопросов в экзамене', field: false},
    NOT_ENOUGH_ANSWERS:{text: 'Количество вариантов ответа для вопроса меньше минимально допустимого', field: false},
    CORRECT_ANSWER_NUMBER_NOT_SET:{text: 'Номер правильного ответа не указан', field: false},
    INVALID_CORRECT_ANSWER_NUMBER:{text: 'Номер правильного ответа меньше 1 или больше числа вариантов ответа', field: false},
    EMPTY_ANSWER_BODY:{text: 'Пустой текст ответа', field: false},
    WRONG_QUESTIONS_COUNT_PER_EXAM:{text: 'Количество вопросов на экзамене меньше минимально допустимого', field: false},
    WRONG_EXAM_TIME:{text: 'Время, отводимое на экзамен, меньше минимально допустимого', field: false},
    EXAM_ALREADY_PASSED:{text: 'Этот экзамен студент уже сдал', field: false},
    EXAM_NOT_TAKEN:{text: 'Попытка послать ответы , не получив предварительно экзамен', field: false},
    EXAM_TIME_IS_OVER:{text: 'Время, отводимое на экзамен, закончилось, ответы не будут приняты', field: false},
    WRONG_SOLUTION_ANSWERS_NUMBER:{text: 'Посланное количество ответов не равно количеству вопросов в экзамене', field: false},
    WRONG_ANSWER_NUMBER:{text: 'Недопустимый номер ответа для вопроса', field: false},
    DATABASE_ERROR:{text: 'Произошла ошибка при работе с БД', field: false}
});
